const categories: string[] = [
  "backgrounds",
  "fashion",
  "nature",
  "science",
  "education",
  "feelings",
  "health",
  "people",
  "religion",
  "places",
  "animals",
  "industry",
  "computer",
  "food",
  "sports",
  "transportation",
  "travel",
  "buildings",
  "business",
  "music",
]

const myFilterArray = {
  Order: ["popular", "latest"],
  Orientataion: ["all", "horizontal", "vertical"],
  Type: ["all", "photo", "illustration", "vector"],
  Colors: [
    "grayscale",
    "transparent",
    "red",
    "orange",
    "yellow",
    "green",
    "turquoise",
    "blue",
    "lilac",
    "pink",
    "white",
    "gray",
    "black",
    "brown",
  ],
}

export default { categories, myFilterArray }
